global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'threadit-api'
    static_configs:
      - targets: ['threadit.site']
    metrics_path: '/metrics'
    scheme: 'https'